### PR TITLE
Switch to Chumsky for parsing

### PR DESCRIPTION
**Pull request by clarkmcc**
Working on a [chumsky parser](https://github.com/zesterer/chumsky). Has some benefits:
* Easier to read and modify than LALRPOP grammar
* Much better error reporting and syntax assistance

### CODE REVIEW

**Comment by hardbyte** [comment]
👀  I've been doing something similar while learning Rust in https://github.com/hardbyte/common-expression-language if you want to collaborate/steal.

**Comment by clarkmcc** [comment]
@hardbyte Ooo very nice! I hit a wall on the chumsky parser and never got around to it again. I will definitely be doing a bit of stealing, or if you're interested, push a PR!

**Comment by hardbyte** [comment]
Cool I'm very keen to combine efforts. Keep in mind I'm new at rust though!

First I had a go at getting your branch going - I wired up your chumsky parser to your CLI but evaluating an expression seemed to quickly take up all my ram. 

Then I noticed that you were using the pre-release of Chumsky 1.0.0 so I thought a good first step would be porting my parser to the same version so I can hopefully copy some of the implementation across. There were a few api changes between 0.9.2 and 1.0.0-alpha.4 and I'd implemented my parser on `char` rather than `&str`. 

I've updated my code with the glaring exception that my `.collect()` calls are no longer compiling... I've pushed what I have to https://github.com/hardbyte/common-expression-language/pull/5 if you felt like taking a look.

Another option might be to use the latest stable version of Chumsky with my parser (adapted for your AST).

**Comment by clarkmcc** [comment]
That was the wall I hit, I think there's a left fold somewhere in the code for recursive expressions that shouldn't be used. I briefly discussed it with the chumsky author but I didn't get too far.

Yeah that final option seems like a good route to take. How much of the parsing is currently supported right now? I think I noticed at least one to-do item last I checked?

**Comment by hardbyte** [comment]
Hmm hopefully together we can solve it - I think I've run into the same issue with an infinity recursive definition now. I've started porting across to your AST in https://github.com/hardbyte/common-expression-language/pull/6

Most of the grammar is supported in my parser - haven't done `in` relation, FieldInits, conditionals or ternaries. But by far the biggest issue is I haven't gotten recursive members working trying to follow the grammar. 

I'm keen to try out the pratt  parser that has landed in chumsky but figured a basic version that follows the grammar would be a good starting point. 

Do you think these folds in the `expr` definition could be part of the issue? They seem reasonable to me...

```rust
        let product_div_op = op('*')
            .to(ArithmeticOp::Multiply)
            .or(op('/').to(ArithmeticOp::Divide));

        let multiplication = unary
            .clone()
            .then(product_div_op.then(unary.clone()).repeated())
            .foldl(|lhs, (binary_op, rhs)| {
                Expression::Arithmetic(Box::new(lhs), binary_op, Box::new(rhs))
            })
            .labelled("product_or_division")
            .boxed();

        let sum_sub_op = op('+')
            .to(ArithmeticOp::Add)
            .or(op('-').to(ArithmeticOp::Subtract));

        let addition = multiplication
            .clone()
            .then(sum_sub_op.then(multiplication.clone()).repeated())
            .foldl(|lhs, (op, rhs)| Expression::Arithmetic(Box::new(lhs), op, Box::new(rhs)))
            .labelled("sub_or_sub")
            .boxed();
```

**Comment by clarkmcc** [comment]
@hardbyte fantastic! I want to take a look at this but am a little preoccupied with https://github.com/clarkmcc/cel-rust/pull/11. Will get back to this as soon as I can.

**Comment by hardbyte** [comment]
Fair enough!

I'll open an issue in this repo to track the next steps as it might not make sense to work from this branch to integrate.

**Comment by hardbyte** [comment]
Oh, did you intend to disable issues in this repo?

In any case, I've merged in those changes to my main branch and finished everything in the parser except FieldInits. I think the next steps are:
- a small refactor PR in this repository to hide larlpop internals and expose a parser function and parser errors from your cel-parser crate?
- a bigger PR to replace this one with the work I've done in my repo

How does that sound?

**Comment by clarkmcc** [comment]
Huh, weird not sure how issues got disabled. Sorry about that! I've re-enabled them. Yes, this makes good sense to me. At some point I'd also like to benchmark LALRPOP vs Chumsky. If the performance differences are notable enough, we might keep both parsers available behind feature flags where the advantage to Chumsky is better parsing error messages. But we can cross that bridge once we have parsing results. I can work up a benchmark for the parser in the mean time.

**Comment by clarkmcc** [comment]
On a totally unrelated note, I read through your readme and found the reference to the [cel-go unit tests](https://github.com/google/cel-spec/blob/master/tests/simple/testdata/basic.textproto). I love the idea of testing against those same tests. I will definitely be looking at that in the near future!

**Comment by clarkmcc** [comment]
Alright, I've just released the latest project I was working on and now have some free cycles to look at this again. Where are we at on this, and what makes the most sense for me to work on?

**Comment by hardbyte** [comment]
Awesome, I've written up everything in this issue https://github.com/clarkmcc/cel-rust/issues/14

The short version is I think my chumsky based parser is now slightly ahead feature-wise to the existing lalrpop one, although I'm sure there will be corner cases to hunt down. I'll open a PR to replace this one - adding support for the chumsky parser rather than switching it out entirely. Once I can run the tests I'll post an update with any differences found.

Do you want to take on the benchmarking and/or testing with the cel-go data?

**Comment by clarkmcc** [comment]
Looking forward to reviewing! Yes, I can definitely take benchmark and tests.

**Pull request closed without merging**
